apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: catalog-tronghuy0104
  labels:
    app: catalog-redis
spec:
  containers:
    - name: redis
      image: redis:7
      ports:
        - containerPort: 6379